// Code generated by go-swagger; DO NOT EDIT.

package counter_samples

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new counter samples API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for counter samples API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
PostOrganizationApisCltTestRunsTestRunIDCountersamples post organization apis clt test runs test run ID countersamples API
*/
func (a *Client) PostOrganizationApisCltTestRunsTestRunIDCountersamples(params *PostOrganizationApisCltTestRunsTestRunIDCountersamplesParams, authInfo runtime.ClientAuthInfoWriter) (*PostOrganizationApisCltTestRunsTestRunIDCountersamplesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostOrganizationApisCltTestRunsTestRunIDCountersamplesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PostOrganizationApisCltTestRunsTestRunIDCountersamples",
		Method:             "POST",
		PathPattern:        "/{organization}/_apis/clt/testRuns/{testRunId}/countersamples",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostOrganizationApisCltTestRunsTestRunIDCountersamplesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PostOrganizationApisCltTestRunsTestRunIDCountersamplesOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
