// Code generated by go-swagger; DO NOT EDIT.

package badge

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new badge API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for badge API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetBuildBadgeData Gets a badge that indicates the status of the most recent build for the specified branch.
*/
func (a *Client) GetBuildBadgeData(params *GetBuildBadgeDataParams, authInfo runtime.ClientAuthInfoWriter) (*GetBuildBadgeDataOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetBuildBadgeDataParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Get Build Badge Data",
		Method:             "GET",
		PathPattern:        "/{organization}/{project}/_apis/build/repos/{repoType}/badge",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetBuildBadgeDataReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetBuildBadgeDataOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
