// Code generated by go-swagger; DO NOT EDIT.

package feed_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteFeedParams creates a new DeleteFeedParams object
// with the default values initialized.
func NewDeleteFeedParams() *DeleteFeedParams {
	var ()
	return &DeleteFeedParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteFeedParamsWithTimeout creates a new DeleteFeedParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteFeedParamsWithTimeout(timeout time.Duration) *DeleteFeedParams {
	var ()
	return &DeleteFeedParams{

		timeout: timeout,
	}
}

// NewDeleteFeedParamsWithContext creates a new DeleteFeedParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteFeedParamsWithContext(ctx context.Context) *DeleteFeedParams {
	var ()
	return &DeleteFeedParams{

		Context: ctx,
	}
}

// NewDeleteFeedParamsWithHTTPClient creates a new DeleteFeedParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteFeedParamsWithHTTPClient(client *http.Client) *DeleteFeedParams {
	var ()
	return &DeleteFeedParams{
		HTTPClient: client,
	}
}

/*DeleteFeedParams contains all the parameters to send to the API endpoint
for the delete feed operation typically these are written to a http.Request
*/
type DeleteFeedParams struct {

	/*APIVersion
	  Version of the API to use.  This should be set to '5.1-preview.1' to use this version of the api.

	*/
	APIVersion string
	/*FeedID
	  Name or Id of the feed.

	*/
	FeedID string
	/*Organization
	  The name of the Azure DevOps organization.

	*/
	Organization string
	/*Project
	  Project ID or project name

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete feed params
func (o *DeleteFeedParams) WithTimeout(timeout time.Duration) *DeleteFeedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete feed params
func (o *DeleteFeedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete feed params
func (o *DeleteFeedParams) WithContext(ctx context.Context) *DeleteFeedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete feed params
func (o *DeleteFeedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete feed params
func (o *DeleteFeedParams) WithHTTPClient(client *http.Client) *DeleteFeedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete feed params
func (o *DeleteFeedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIVersion adds the aPIVersion to the delete feed params
func (o *DeleteFeedParams) WithAPIVersion(aPIVersion string) *DeleteFeedParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the delete feed params
func (o *DeleteFeedParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithFeedID adds the feedID to the delete feed params
func (o *DeleteFeedParams) WithFeedID(feedID string) *DeleteFeedParams {
	o.SetFeedID(feedID)
	return o
}

// SetFeedID adds the feedId to the delete feed params
func (o *DeleteFeedParams) SetFeedID(feedID string) {
	o.FeedID = feedID
}

// WithOrganization adds the organization to the delete feed params
func (o *DeleteFeedParams) WithOrganization(organization string) *DeleteFeedParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the delete feed params
func (o *DeleteFeedParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithProject adds the project to the delete feed params
func (o *DeleteFeedParams) WithProject(project string) *DeleteFeedParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the delete feed params
func (o *DeleteFeedParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteFeedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	// path param feedId
	if err := r.SetPathParam("feedId", o.FeedID); err != nil {
		return err
	}

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
