// Code generated by go-swagger; DO NOT EDIT.

package feed_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetFeedPermissionsParams creates a new GetFeedPermissionsParams object
// with the default values initialized.
func NewGetFeedPermissionsParams() *GetFeedPermissionsParams {
	var ()
	return &GetFeedPermissionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetFeedPermissionsParamsWithTimeout creates a new GetFeedPermissionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetFeedPermissionsParamsWithTimeout(timeout time.Duration) *GetFeedPermissionsParams {
	var ()
	return &GetFeedPermissionsParams{

		timeout: timeout,
	}
}

// NewGetFeedPermissionsParamsWithContext creates a new GetFeedPermissionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetFeedPermissionsParamsWithContext(ctx context.Context) *GetFeedPermissionsParams {
	var ()
	return &GetFeedPermissionsParams{

		Context: ctx,
	}
}

// NewGetFeedPermissionsParamsWithHTTPClient creates a new GetFeedPermissionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetFeedPermissionsParamsWithHTTPClient(client *http.Client) *GetFeedPermissionsParams {
	var ()
	return &GetFeedPermissionsParams{
		HTTPClient: client,
	}
}

/*GetFeedPermissionsParams contains all the parameters to send to the API endpoint
for the get feed permissions operation typically these are written to a http.Request
*/
type GetFeedPermissionsParams struct {

	/*APIVersion
	  Version of the API to use.  This should be set to '5.1-preview.1' to use this version of the api.

	*/
	APIVersion string
	/*ExcludeInheritedPermissions
	  True to only return explicitly set permissions on the feed.  Default is false.

	*/
	ExcludeInheritedPermissions *bool
	/*FeedID
	  Name or Id of the feed.

	*/
	FeedID string
	/*IdentityDescriptor
	  Filter permissions to the provided identity.

	*/
	IdentityDescriptor *string
	/*IncludeIds
	  True to include user Ids in the response.  Default is false.

	*/
	IncludeIds *bool
	/*Organization
	  The name of the Azure DevOps organization.

	*/
	Organization string
	/*Project
	  Project ID or project name

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get feed permissions params
func (o *GetFeedPermissionsParams) WithTimeout(timeout time.Duration) *GetFeedPermissionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get feed permissions params
func (o *GetFeedPermissionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get feed permissions params
func (o *GetFeedPermissionsParams) WithContext(ctx context.Context) *GetFeedPermissionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get feed permissions params
func (o *GetFeedPermissionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get feed permissions params
func (o *GetFeedPermissionsParams) WithHTTPClient(client *http.Client) *GetFeedPermissionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get feed permissions params
func (o *GetFeedPermissionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIVersion adds the aPIVersion to the get feed permissions params
func (o *GetFeedPermissionsParams) WithAPIVersion(aPIVersion string) *GetFeedPermissionsParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the get feed permissions params
func (o *GetFeedPermissionsParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithExcludeInheritedPermissions adds the excludeInheritedPermissions to the get feed permissions params
func (o *GetFeedPermissionsParams) WithExcludeInheritedPermissions(excludeInheritedPermissions *bool) *GetFeedPermissionsParams {
	o.SetExcludeInheritedPermissions(excludeInheritedPermissions)
	return o
}

// SetExcludeInheritedPermissions adds the excludeInheritedPermissions to the get feed permissions params
func (o *GetFeedPermissionsParams) SetExcludeInheritedPermissions(excludeInheritedPermissions *bool) {
	o.ExcludeInheritedPermissions = excludeInheritedPermissions
}

// WithFeedID adds the feedID to the get feed permissions params
func (o *GetFeedPermissionsParams) WithFeedID(feedID string) *GetFeedPermissionsParams {
	o.SetFeedID(feedID)
	return o
}

// SetFeedID adds the feedId to the get feed permissions params
func (o *GetFeedPermissionsParams) SetFeedID(feedID string) {
	o.FeedID = feedID
}

// WithIdentityDescriptor adds the identityDescriptor to the get feed permissions params
func (o *GetFeedPermissionsParams) WithIdentityDescriptor(identityDescriptor *string) *GetFeedPermissionsParams {
	o.SetIdentityDescriptor(identityDescriptor)
	return o
}

// SetIdentityDescriptor adds the identityDescriptor to the get feed permissions params
func (o *GetFeedPermissionsParams) SetIdentityDescriptor(identityDescriptor *string) {
	o.IdentityDescriptor = identityDescriptor
}

// WithIncludeIds adds the includeIds to the get feed permissions params
func (o *GetFeedPermissionsParams) WithIncludeIds(includeIds *bool) *GetFeedPermissionsParams {
	o.SetIncludeIds(includeIds)
	return o
}

// SetIncludeIds adds the includeIds to the get feed permissions params
func (o *GetFeedPermissionsParams) SetIncludeIds(includeIds *bool) {
	o.IncludeIds = includeIds
}

// WithOrganization adds the organization to the get feed permissions params
func (o *GetFeedPermissionsParams) WithOrganization(organization string) *GetFeedPermissionsParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the get feed permissions params
func (o *GetFeedPermissionsParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithProject adds the project to the get feed permissions params
func (o *GetFeedPermissionsParams) WithProject(project string) *GetFeedPermissionsParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the get feed permissions params
func (o *GetFeedPermissionsParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *GetFeedPermissionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	if o.ExcludeInheritedPermissions != nil {

		// query param excludeInheritedPermissions
		var qrExcludeInheritedPermissions bool
		if o.ExcludeInheritedPermissions != nil {
			qrExcludeInheritedPermissions = *o.ExcludeInheritedPermissions
		}
		qExcludeInheritedPermissions := swag.FormatBool(qrExcludeInheritedPermissions)
		if qExcludeInheritedPermissions != "" {
			if err := r.SetQueryParam("excludeInheritedPermissions", qExcludeInheritedPermissions); err != nil {
				return err
			}
		}

	}

	// path param feedId
	if err := r.SetPathParam("feedId", o.FeedID); err != nil {
		return err
	}

	if o.IdentityDescriptor != nil {

		// query param identityDescriptor
		var qrIdentityDescriptor string
		if o.IdentityDescriptor != nil {
			qrIdentityDescriptor = *o.IdentityDescriptor
		}
		qIdentityDescriptor := qrIdentityDescriptor
		if qIdentityDescriptor != "" {
			if err := r.SetQueryParam("identityDescriptor", qIdentityDescriptor); err != nil {
				return err
			}
		}

	}

	if o.IncludeIds != nil {

		// query param includeIds
		var qrIncludeIds bool
		if o.IncludeIds != nil {
			qrIncludeIds = *o.IncludeIds
		}
		qIncludeIds := swag.FormatBool(qrIncludeIds)
		if qIncludeIds != "" {
			if err := r.SetQueryParam("includeIds", qIncludeIds); err != nil {
				return err
			}
		}

	}

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
