// Code generated by go-swagger; DO NOT EDIT.

package feed_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "azure-devops/5.1/models"
)

// NewSetFeedPermissionsParams creates a new SetFeedPermissionsParams object
// with the default values initialized.
func NewSetFeedPermissionsParams() *SetFeedPermissionsParams {
	var ()
	return &SetFeedPermissionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetFeedPermissionsParamsWithTimeout creates a new SetFeedPermissionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetFeedPermissionsParamsWithTimeout(timeout time.Duration) *SetFeedPermissionsParams {
	var ()
	return &SetFeedPermissionsParams{

		timeout: timeout,
	}
}

// NewSetFeedPermissionsParamsWithContext creates a new SetFeedPermissionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetFeedPermissionsParamsWithContext(ctx context.Context) *SetFeedPermissionsParams {
	var ()
	return &SetFeedPermissionsParams{

		Context: ctx,
	}
}

// NewSetFeedPermissionsParamsWithHTTPClient creates a new SetFeedPermissionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetFeedPermissionsParamsWithHTTPClient(client *http.Client) *SetFeedPermissionsParams {
	var ()
	return &SetFeedPermissionsParams{
		HTTPClient: client,
	}
}

/*SetFeedPermissionsParams contains all the parameters to send to the API endpoint
for the set feed permissions operation typically these are written to a http.Request
*/
type SetFeedPermissionsParams struct {

	/*APIVersion
	  Version of the API to use.  This should be set to '5.1-preview.1' to use this version of the api.

	*/
	APIVersion string
	/*Body
	  Permissions to set.

	*/
	Body []*models.FeedPermission
	/*FeedID
	  Name or Id of the feed.

	*/
	FeedID string
	/*Organization
	  The name of the Azure DevOps organization.

	*/
	Organization string
	/*Project
	  Project ID or project name

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set feed permissions params
func (o *SetFeedPermissionsParams) WithTimeout(timeout time.Duration) *SetFeedPermissionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set feed permissions params
func (o *SetFeedPermissionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set feed permissions params
func (o *SetFeedPermissionsParams) WithContext(ctx context.Context) *SetFeedPermissionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set feed permissions params
func (o *SetFeedPermissionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set feed permissions params
func (o *SetFeedPermissionsParams) WithHTTPClient(client *http.Client) *SetFeedPermissionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set feed permissions params
func (o *SetFeedPermissionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIVersion adds the aPIVersion to the set feed permissions params
func (o *SetFeedPermissionsParams) WithAPIVersion(aPIVersion string) *SetFeedPermissionsParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the set feed permissions params
func (o *SetFeedPermissionsParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithBody adds the body to the set feed permissions params
func (o *SetFeedPermissionsParams) WithBody(body []*models.FeedPermission) *SetFeedPermissionsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the set feed permissions params
func (o *SetFeedPermissionsParams) SetBody(body []*models.FeedPermission) {
	o.Body = body
}

// WithFeedID adds the feedID to the set feed permissions params
func (o *SetFeedPermissionsParams) WithFeedID(feedID string) *SetFeedPermissionsParams {
	o.SetFeedID(feedID)
	return o
}

// SetFeedID adds the feedId to the set feed permissions params
func (o *SetFeedPermissionsParams) SetFeedID(feedID string) {
	o.FeedID = feedID
}

// WithOrganization adds the organization to the set feed permissions params
func (o *SetFeedPermissionsParams) WithOrganization(organization string) *SetFeedPermissionsParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the set feed permissions params
func (o *SetFeedPermissionsParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithProject adds the project to the set feed permissions params
func (o *SetFeedPermissionsParams) WithProject(project string) *SetFeedPermissionsParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the set feed permissions params
func (o *SetFeedPermissionsParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *SetFeedPermissionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param feedId
	if err := r.SetPathParam("feedId", o.FeedID); err != nil {
		return err
	}

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
