// Code generated by go-swagger; DO NOT EDIT.

package feed_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "azure-devops/5.1/models"
)

// NewUpdateFeedParams creates a new UpdateFeedParams object
// with the default values initialized.
func NewUpdateFeedParams() *UpdateFeedParams {
	var ()
	return &UpdateFeedParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateFeedParamsWithTimeout creates a new UpdateFeedParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateFeedParamsWithTimeout(timeout time.Duration) *UpdateFeedParams {
	var ()
	return &UpdateFeedParams{

		timeout: timeout,
	}
}

// NewUpdateFeedParamsWithContext creates a new UpdateFeedParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateFeedParamsWithContext(ctx context.Context) *UpdateFeedParams {
	var ()
	return &UpdateFeedParams{

		Context: ctx,
	}
}

// NewUpdateFeedParamsWithHTTPClient creates a new UpdateFeedParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateFeedParamsWithHTTPClient(client *http.Client) *UpdateFeedParams {
	var ()
	return &UpdateFeedParams{
		HTTPClient: client,
	}
}

/*UpdateFeedParams contains all the parameters to send to the API endpoint
for the update feed operation typically these are written to a http.Request
*/
type UpdateFeedParams struct {

	/*APIVersion
	  Version of the API to use.  This should be set to '5.1-preview.1' to use this version of the api.

	*/
	APIVersion string
	/*Body
	  A JSON object containing the feed settings to be updated.

	*/
	Body *models.FeedUpdate
	/*FeedID
	  Name or Id of the feed.

	*/
	FeedID string
	/*Organization
	  The name of the Azure DevOps organization.

	*/
	Organization string
	/*Project
	  Project ID or project name

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update feed params
func (o *UpdateFeedParams) WithTimeout(timeout time.Duration) *UpdateFeedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update feed params
func (o *UpdateFeedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update feed params
func (o *UpdateFeedParams) WithContext(ctx context.Context) *UpdateFeedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update feed params
func (o *UpdateFeedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update feed params
func (o *UpdateFeedParams) WithHTTPClient(client *http.Client) *UpdateFeedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update feed params
func (o *UpdateFeedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIVersion adds the aPIVersion to the update feed params
func (o *UpdateFeedParams) WithAPIVersion(aPIVersion string) *UpdateFeedParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the update feed params
func (o *UpdateFeedParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithBody adds the body to the update feed params
func (o *UpdateFeedParams) WithBody(body *models.FeedUpdate) *UpdateFeedParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update feed params
func (o *UpdateFeedParams) SetBody(body *models.FeedUpdate) {
	o.Body = body
}

// WithFeedID adds the feedID to the update feed params
func (o *UpdateFeedParams) WithFeedID(feedID string) *UpdateFeedParams {
	o.SetFeedID(feedID)
	return o
}

// SetFeedID adds the feedId to the update feed params
func (o *UpdateFeedParams) SetFeedID(feedID string) {
	o.FeedID = feedID
}

// WithOrganization adds the organization to the update feed params
func (o *UpdateFeedParams) WithOrganization(organization string) *UpdateFeedParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the update feed params
func (o *UpdateFeedParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithProject adds the project to the update feed params
func (o *UpdateFeedParams) WithProject(project string) *UpdateFeedParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the update feed params
func (o *UpdateFeedParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateFeedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param feedId
	if err := r.SetPathParam("feedId", o.FeedID); err != nil {
		return err
	}

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
