// Code generated by go-swagger; DO NOT EDIT.

package feed_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "azure-devops/5.1/models"
)

// UpdateFeedReader is a Reader for the UpdateFeed structure.
type UpdateFeedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateFeedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpdateFeedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateFeedOK creates a UpdateFeedOK with default headers values
func NewUpdateFeedOK() *UpdateFeedOK {
	return &UpdateFeedOK{}
}

/*UpdateFeedOK handles this case with default header values.

successful operation
*/
type UpdateFeedOK struct {
	Payload *models.Feed
}

func (o *UpdateFeedOK) Error() string {
	return fmt.Sprintf("[PATCH /{organization}/{project}/_apis/packaging/feeds/{feedId}][%d] updateFeedOK  %+v", 200, o.Payload)
}

func (o *UpdateFeedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Feed)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
