// Code generated by go-swagger; DO NOT EDIT.

package suite_test_case

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRemoveTestCasesFromSuiteParams creates a new RemoveTestCasesFromSuiteParams object
// with the default values initialized.
func NewRemoveTestCasesFromSuiteParams() *RemoveTestCasesFromSuiteParams {
	var ()
	return &RemoveTestCasesFromSuiteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRemoveTestCasesFromSuiteParamsWithTimeout creates a new RemoveTestCasesFromSuiteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRemoveTestCasesFromSuiteParamsWithTimeout(timeout time.Duration) *RemoveTestCasesFromSuiteParams {
	var ()
	return &RemoveTestCasesFromSuiteParams{

		timeout: timeout,
	}
}

// NewRemoveTestCasesFromSuiteParamsWithContext creates a new RemoveTestCasesFromSuiteParams object
// with the default values initialized, and the ability to set a context for a request
func NewRemoveTestCasesFromSuiteParamsWithContext(ctx context.Context) *RemoveTestCasesFromSuiteParams {
	var ()
	return &RemoveTestCasesFromSuiteParams{

		Context: ctx,
	}
}

// NewRemoveTestCasesFromSuiteParamsWithHTTPClient creates a new RemoveTestCasesFromSuiteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRemoveTestCasesFromSuiteParamsWithHTTPClient(client *http.Client) *RemoveTestCasesFromSuiteParams {
	var ()
	return &RemoveTestCasesFromSuiteParams{
		HTTPClient: client,
	}
}

/*RemoveTestCasesFromSuiteParams contains all the parameters to send to the API endpoint
for the remove test cases from suite operation typically these are written to a http.Request
*/
type RemoveTestCasesFromSuiteParams struct {

	/*APIVersion
	  Version of the API to use.  This should be set to '5.1-preview.2' to use this version of the api.

	*/
	APIVersion string
	/*Organization
	  The name of the Azure DevOps organization.

	*/
	Organization string
	/*PlanID
	  ID of the test plan from which test cases are to be removed.

	*/
	PlanID int32
	/*Project
	  Project ID or project name

	*/
	Project string
	/*SuiteID
	  ID of the test suite from which test cases are to be removed.

	*/
	SuiteID int32
	/*TestCaseIds
	  Test Case Ids to be removed.

	*/
	TestCaseIds string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the remove test cases from suite params
func (o *RemoveTestCasesFromSuiteParams) WithTimeout(timeout time.Duration) *RemoveTestCasesFromSuiteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remove test cases from suite params
func (o *RemoveTestCasesFromSuiteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the remove test cases from suite params
func (o *RemoveTestCasesFromSuiteParams) WithContext(ctx context.Context) *RemoveTestCasesFromSuiteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remove test cases from suite params
func (o *RemoveTestCasesFromSuiteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the remove test cases from suite params
func (o *RemoveTestCasesFromSuiteParams) WithHTTPClient(client *http.Client) *RemoveTestCasesFromSuiteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the remove test cases from suite params
func (o *RemoveTestCasesFromSuiteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIVersion adds the aPIVersion to the remove test cases from suite params
func (o *RemoveTestCasesFromSuiteParams) WithAPIVersion(aPIVersion string) *RemoveTestCasesFromSuiteParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the remove test cases from suite params
func (o *RemoveTestCasesFromSuiteParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithOrganization adds the organization to the remove test cases from suite params
func (o *RemoveTestCasesFromSuiteParams) WithOrganization(organization string) *RemoveTestCasesFromSuiteParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the remove test cases from suite params
func (o *RemoveTestCasesFromSuiteParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithPlanID adds the planID to the remove test cases from suite params
func (o *RemoveTestCasesFromSuiteParams) WithPlanID(planID int32) *RemoveTestCasesFromSuiteParams {
	o.SetPlanID(planID)
	return o
}

// SetPlanID adds the planId to the remove test cases from suite params
func (o *RemoveTestCasesFromSuiteParams) SetPlanID(planID int32) {
	o.PlanID = planID
}

// WithProject adds the project to the remove test cases from suite params
func (o *RemoveTestCasesFromSuiteParams) WithProject(project string) *RemoveTestCasesFromSuiteParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the remove test cases from suite params
func (o *RemoveTestCasesFromSuiteParams) SetProject(project string) {
	o.Project = project
}

// WithSuiteID adds the suiteID to the remove test cases from suite params
func (o *RemoveTestCasesFromSuiteParams) WithSuiteID(suiteID int32) *RemoveTestCasesFromSuiteParams {
	o.SetSuiteID(suiteID)
	return o
}

// SetSuiteID adds the suiteId to the remove test cases from suite params
func (o *RemoveTestCasesFromSuiteParams) SetSuiteID(suiteID int32) {
	o.SuiteID = suiteID
}

// WithTestCaseIds adds the testCaseIds to the remove test cases from suite params
func (o *RemoveTestCasesFromSuiteParams) WithTestCaseIds(testCaseIds string) *RemoveTestCasesFromSuiteParams {
	o.SetTestCaseIds(testCaseIds)
	return o
}

// SetTestCaseIds adds the testCaseIds to the remove test cases from suite params
func (o *RemoveTestCasesFromSuiteParams) SetTestCaseIds(testCaseIds string) {
	o.TestCaseIds = testCaseIds
}

// WriteToRequest writes these params to a swagger request
func (o *RemoveTestCasesFromSuiteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param planId
	if err := r.SetPathParam("planId", swag.FormatInt32(o.PlanID)); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	// path param suiteId
	if err := r.SetPathParam("suiteId", swag.FormatInt32(o.SuiteID)); err != nil {
		return err
	}

	// path param testCaseIds
	if err := r.SetPathParam("testCaseIds", o.TestCaseIds); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
