// Code generated by go-swagger; DO NOT EDIT.

package cardrulesettings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "azure-devops/5.1/models"
)

// NewUpdateTaskboardCardRuleSettingsParams creates a new UpdateTaskboardCardRuleSettingsParams object
// with the default values initialized.
func NewUpdateTaskboardCardRuleSettingsParams() *UpdateTaskboardCardRuleSettingsParams {
	var ()
	return &UpdateTaskboardCardRuleSettingsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateTaskboardCardRuleSettingsParamsWithTimeout creates a new UpdateTaskboardCardRuleSettingsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateTaskboardCardRuleSettingsParamsWithTimeout(timeout time.Duration) *UpdateTaskboardCardRuleSettingsParams {
	var ()
	return &UpdateTaskboardCardRuleSettingsParams{

		timeout: timeout,
	}
}

// NewUpdateTaskboardCardRuleSettingsParamsWithContext creates a new UpdateTaskboardCardRuleSettingsParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateTaskboardCardRuleSettingsParamsWithContext(ctx context.Context) *UpdateTaskboardCardRuleSettingsParams {
	var ()
	return &UpdateTaskboardCardRuleSettingsParams{

		Context: ctx,
	}
}

// NewUpdateTaskboardCardRuleSettingsParamsWithHTTPClient creates a new UpdateTaskboardCardRuleSettingsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateTaskboardCardRuleSettingsParamsWithHTTPClient(client *http.Client) *UpdateTaskboardCardRuleSettingsParams {
	var ()
	return &UpdateTaskboardCardRuleSettingsParams{
		HTTPClient: client,
	}
}

/*UpdateTaskboardCardRuleSettingsParams contains all the parameters to send to the API endpoint
for the update taskboard card rule settings operation typically these are written to a http.Request
*/
type UpdateTaskboardCardRuleSettingsParams struct {

	/*APIVersion
	  Version of the API to use.  This should be set to '5.1-preview.2' to use this version of the api.

	*/
	APIVersion string
	/*Body*/
	Body *models.BoardCardRuleSettings
	/*Organization
	  The name of the Azure DevOps organization.

	*/
	Organization string
	/*Project
	  Project ID or project name

	*/
	Project string
	/*Team
	  Team ID or team name

	*/
	Team string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update taskboard card rule settings params
func (o *UpdateTaskboardCardRuleSettingsParams) WithTimeout(timeout time.Duration) *UpdateTaskboardCardRuleSettingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update taskboard card rule settings params
func (o *UpdateTaskboardCardRuleSettingsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update taskboard card rule settings params
func (o *UpdateTaskboardCardRuleSettingsParams) WithContext(ctx context.Context) *UpdateTaskboardCardRuleSettingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update taskboard card rule settings params
func (o *UpdateTaskboardCardRuleSettingsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update taskboard card rule settings params
func (o *UpdateTaskboardCardRuleSettingsParams) WithHTTPClient(client *http.Client) *UpdateTaskboardCardRuleSettingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update taskboard card rule settings params
func (o *UpdateTaskboardCardRuleSettingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIVersion adds the aPIVersion to the update taskboard card rule settings params
func (o *UpdateTaskboardCardRuleSettingsParams) WithAPIVersion(aPIVersion string) *UpdateTaskboardCardRuleSettingsParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the update taskboard card rule settings params
func (o *UpdateTaskboardCardRuleSettingsParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithBody adds the body to the update taskboard card rule settings params
func (o *UpdateTaskboardCardRuleSettingsParams) WithBody(body *models.BoardCardRuleSettings) *UpdateTaskboardCardRuleSettingsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update taskboard card rule settings params
func (o *UpdateTaskboardCardRuleSettingsParams) SetBody(body *models.BoardCardRuleSettings) {
	o.Body = body
}

// WithOrganization adds the organization to the update taskboard card rule settings params
func (o *UpdateTaskboardCardRuleSettingsParams) WithOrganization(organization string) *UpdateTaskboardCardRuleSettingsParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the update taskboard card rule settings params
func (o *UpdateTaskboardCardRuleSettingsParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithProject adds the project to the update taskboard card rule settings params
func (o *UpdateTaskboardCardRuleSettingsParams) WithProject(project string) *UpdateTaskboardCardRuleSettingsParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the update taskboard card rule settings params
func (o *UpdateTaskboardCardRuleSettingsParams) SetProject(project string) {
	o.Project = project
}

// WithTeam adds the team to the update taskboard card rule settings params
func (o *UpdateTaskboardCardRuleSettingsParams) WithTeam(team string) *UpdateTaskboardCardRuleSettingsParams {
	o.SetTeam(team)
	return o
}

// SetTeam adds the team to the update taskboard card rule settings params
func (o *UpdateTaskboardCardRuleSettingsParams) SetTeam(team string) {
	o.Team = team
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateTaskboardCardRuleSettingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	// path param team
	if err := r.SetPathParam("team", o.Team); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
