// Code generated by go-swagger; DO NOT EDIT.

package dashboards

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "azure-devops/5.1/models"
)

// ReplaceDashboardReader is a Reader for the ReplaceDashboard structure.
type ReplaceDashboardReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReplaceDashboardReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewReplaceDashboardOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewReplaceDashboardOK creates a ReplaceDashboardOK with default headers values
func NewReplaceDashboardOK() *ReplaceDashboardOK {
	return &ReplaceDashboardOK{}
}

/*ReplaceDashboardOK handles this case with default header values.

successful operation
*/
type ReplaceDashboardOK struct {
	Payload *models.Dashboard
}

func (o *ReplaceDashboardOK) Error() string {
	return fmt.Sprintf("[PUT /{organization}/{project}/{team}/_apis/dashboard/dashboards/{dashboardId}][%d] replaceDashboardOK  %+v", 200, o.Payload)
}

func (o *ReplaceDashboardOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Dashboard)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
