// Code generated by go-swagger; DO NOT EDIT.

package iterations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetParams creates a new GetParams object
// with the default values initialized.
func NewGetParams() *GetParams {
	var ()
	return &GetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetParamsWithTimeout creates a new GetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetParamsWithTimeout(timeout time.Duration) *GetParams {
	var ()
	return &GetParams{

		timeout: timeout,
	}
}

// NewGetParamsWithContext creates a new GetParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetParamsWithContext(ctx context.Context) *GetParams {
	var ()
	return &GetParams{

		Context: ctx,
	}
}

// NewGetParamsWithHTTPClient creates a new GetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetParamsWithHTTPClient(client *http.Client) *GetParams {
	var ()
	return &GetParams{
		HTTPClient: client,
	}
}

/*GetParams contains all the parameters to send to the API endpoint
for the get operation typically these are written to a http.Request
*/
type GetParams struct {

	/*APIVersion
	  Version of the API to use.  This should be set to '5.1-preview.3' to use this version of the api.

	*/
	APIVersion string
	/*IncludeActionResults
	  Include result details for each action performed in the test iteration. ActionResults refer to outcome (pass/fail) of test steps that are executed as part of a running a manual test. Including the ActionResults flag gets the outcome of test steps in the actionResults section and test parameters in the parameters section for each test iteration.

	*/
	IncludeActionResults *bool
	/*IterationID
	  Id of the test results Iteration.

	*/
	IterationID int32
	/*Organization
	  The name of the Azure DevOps organization.

	*/
	Organization string
	/*Project
	  Project ID or project name

	*/
	Project string
	/*RunID
	  ID of the test run that contains the result.

	*/
	RunID int32
	/*TestCaseResultID
	  ID of the test result that contains the iterations.

	*/
	TestCaseResultID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get params
func (o *GetParams) WithTimeout(timeout time.Duration) *GetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get params
func (o *GetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get params
func (o *GetParams) WithContext(ctx context.Context) *GetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get params
func (o *GetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get params
func (o *GetParams) WithHTTPClient(client *http.Client) *GetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get params
func (o *GetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIVersion adds the aPIVersion to the get params
func (o *GetParams) WithAPIVersion(aPIVersion string) *GetParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the get params
func (o *GetParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithIncludeActionResults adds the includeActionResults to the get params
func (o *GetParams) WithIncludeActionResults(includeActionResults *bool) *GetParams {
	o.SetIncludeActionResults(includeActionResults)
	return o
}

// SetIncludeActionResults adds the includeActionResults to the get params
func (o *GetParams) SetIncludeActionResults(includeActionResults *bool) {
	o.IncludeActionResults = includeActionResults
}

// WithIterationID adds the iterationID to the get params
func (o *GetParams) WithIterationID(iterationID int32) *GetParams {
	o.SetIterationID(iterationID)
	return o
}

// SetIterationID adds the iterationId to the get params
func (o *GetParams) SetIterationID(iterationID int32) {
	o.IterationID = iterationID
}

// WithOrganization adds the organization to the get params
func (o *GetParams) WithOrganization(organization string) *GetParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the get params
func (o *GetParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithProject adds the project to the get params
func (o *GetParams) WithProject(project string) *GetParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the get params
func (o *GetParams) SetProject(project string) {
	o.Project = project
}

// WithRunID adds the runID to the get params
func (o *GetParams) WithRunID(runID int32) *GetParams {
	o.SetRunID(runID)
	return o
}

// SetRunID adds the runId to the get params
func (o *GetParams) SetRunID(runID int32) {
	o.RunID = runID
}

// WithTestCaseResultID adds the testCaseResultID to the get params
func (o *GetParams) WithTestCaseResultID(testCaseResultID int32) *GetParams {
	o.SetTestCaseResultID(testCaseResultID)
	return o
}

// SetTestCaseResultID adds the testCaseResultId to the get params
func (o *GetParams) SetTestCaseResultID(testCaseResultID int32) {
	o.TestCaseResultID = testCaseResultID
}

// WriteToRequest writes these params to a swagger request
func (o *GetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	if o.IncludeActionResults != nil {

		// query param includeActionResults
		var qrIncludeActionResults bool
		if o.IncludeActionResults != nil {
			qrIncludeActionResults = *o.IncludeActionResults
		}
		qIncludeActionResults := swag.FormatBool(qrIncludeActionResults)
		if qIncludeActionResults != "" {
			if err := r.SetQueryParam("includeActionResults", qIncludeActionResults); err != nil {
				return err
			}
		}

	}

	// path param iterationId
	if err := r.SetPathParam("iterationId", swag.FormatInt32(o.IterationID)); err != nil {
		return err
	}

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	// path param runId
	if err := r.SetPathParam("runId", swag.FormatInt32(o.RunID)); err != nil {
		return err
	}

	// path param testCaseResultId
	if err := r.SetPathParam("testCaseResultId", swag.FormatInt32(o.TestCaseResultID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
