// Code generated by go-swagger; DO NOT EDIT.

package source_providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "azure-devops/5.1/models"
)

// GetPullRequestReader is a Reader for the GetPullRequest structure.
type GetPullRequestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPullRequestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPullRequestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPullRequestOK creates a GetPullRequestOK with default headers values
func NewGetPullRequestOK() *GetPullRequestOK {
	return &GetPullRequestOK{}
}

/*GetPullRequestOK handles this case with default header values.

successful operation
*/
type GetPullRequestOK struct {
	Payload *models.PullRequest
}

func (o *GetPullRequestOK) Error() string {
	return fmt.Sprintf("[GET /{organization}/{project}/_apis/sourceProviders/{providerName}/pullrequests/{pullRequestId}][%d] getPullRequestOK  %+v", 200, o.Payload)
}

func (o *GetPullRequestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PullRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
