// Code generated by go-swagger; DO NOT EDIT.

package user_entitlements

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "azure-devops/5.1/models"
)

// GetUserEntitlementsReader is a Reader for the GetUserEntitlements structure.
type GetUserEntitlementsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUserEntitlementsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetUserEntitlementsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetUserEntitlementsOK creates a GetUserEntitlementsOK with default headers values
func NewGetUserEntitlementsOK() *GetUserEntitlementsOK {
	return &GetUserEntitlementsOK{}
}

/*GetUserEntitlementsOK handles this case with default header values.

successful operation
*/
type GetUserEntitlementsOK struct {
	Payload *models.PagedGraphMemberList
}

func (o *GetUserEntitlementsOK) Error() string {
	return fmt.Sprintf("[GET /{organization}/_apis/userentitlements][%d] getUserEntitlementsOK  %+v", 200, o.Payload)
}

func (o *GetUserEntitlementsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PagedGraphMemberList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
