// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// AgentRefreshMessage agent refresh message
// swagger:model AgentRefreshMessage
type AgentRefreshMessage struct {

	// agent Id
	AgentID int32 `json:"agentId,omitempty"`

	// target version
	TargetVersion string `json:"targetVersion,omitempty"`

	// timeout
	Timeout string `json:"timeout,omitempty"`
}

// Validate validates this agent refresh message
func (m *AgentRefreshMessage) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AgentRefreshMessage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AgentRefreshMessage) UnmarshalBinary(b []byte) error {
	var res AgentRefreshMessage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
