// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// BuildArtifact Represents an artifact produced by a build.
// swagger:model BuildArtifact
type BuildArtifact struct {

	// The artifact ID.
	ID int32 `json:"id,omitempty"`

	// The name of the artifact.
	Name string `json:"name,omitempty"`

	// The actual resource.
	Resource *ArtifactResource `json:"resource,omitempty"`

	// The artifact source, which will be the ID of the job that produced this artifact.
	Source string `json:"source,omitempty"`
}

// Validate validates this build artifact
func (m *BuildArtifact) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateResource(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BuildArtifact) validateResource(formats strfmt.Registry) error {

	if swag.IsZero(m.Resource) { // not required
		return nil
	}

	if m.Resource != nil {
		if err := m.Resource.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resource")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *BuildArtifact) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BuildArtifact) UnmarshalBinary(b []byte) error {
	var res BuildArtifact
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
