// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// BuildOptionGroupDefinition Represents a group of inputs for a build option.
// swagger:model BuildOptionGroupDefinition
type BuildOptionGroupDefinition struct {

	// The name of the group to display in the UI.
	DisplayName string `json:"displayName,omitempty"`

	// Indicates whether the group is initially displayed as expanded in the UI.
	IsExpanded bool `json:"isExpanded,omitempty"`

	// The internal name of the group.
	Name string `json:"name,omitempty"`
}

// Validate validates this build option group definition
func (m *BuildOptionGroupDefinition) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BuildOptionGroupDefinition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BuildOptionGroupDefinition) UnmarshalBinary(b []byte) error {
	var res BuildOptionGroupDefinition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
