// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CounterVariable counter variable
// swagger:model CounterVariable
type CounterVariable struct {

	// prefix
	Prefix string `json:"prefix,omitempty"`

	// seed
	Seed int32 `json:"seed,omitempty"`

	// value
	Value int32 `json:"value,omitempty"`
}

// Validate validates this counter variable
func (m *CounterVariable) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CounterVariable) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CounterVariable) UnmarshalBinary(b []byte) error {
	var res CounterVariable
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
