// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// DeploymentGatesChangeEvent deployment gates change event
// swagger:model DeploymentGatesChangeEvent
type DeploymentGatesChangeEvent struct {

	// gate names
	GateNames []string `json:"gateNames"`
}

// Validate validates this deployment gates change event
func (m *DeploymentGatesChangeEvent) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeploymentGatesChangeEvent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeploymentGatesChangeEvent) UnmarshalBinary(b []byte) error {
	var res DeploymentGatesChangeEvent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
