// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// DeploymentTargetUpdateParameter Deployment target update parameter.
// swagger:model DeploymentTargetUpdateParameter
type DeploymentTargetUpdateParameter struct {

	// Identifier of the deployment target.
	ID int32 `json:"id,omitempty"`

	// tags
	Tags []string `json:"tags"`
}

// Validate validates this deployment target update parameter
func (m *DeploymentTargetUpdateParameter) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeploymentTargetUpdateParameter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeploymentTargetUpdateParameter) UnmarshalBinary(b []byte) error {
	var res DeploymentTargetUpdateParameter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
