// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// EnvironmentCreateParameter Properties to create Environment.
// swagger:model EnvironmentCreateParameter
type EnvironmentCreateParameter struct {

	// Description of the environment.
	Description string `json:"description,omitempty"`

	// Name of the environment.
	Name string `json:"name,omitempty"`
}

// Validate validates this environment create parameter
func (m *EnvironmentCreateParameter) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EnvironmentCreateParameter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EnvironmentCreateParameter) UnmarshalBinary(b []byte) error {
	var res EnvironmentCreateParameter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
