// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ExtensionBadge extension badge
// swagger:model ExtensionBadge
type ExtensionBadge struct {

	// description
	Description string `json:"description,omitempty"`

	// img Uri
	ImgURI string `json:"imgUri,omitempty"`

	// link
	Link string `json:"link,omitempty"`
}

// Validate validates this extension badge
func (m *ExtensionBadge) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ExtensionBadge) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExtensionBadge) UnmarshalBinary(b []byte) error {
	var res ExtensionBadge
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
