// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// FilterGroup filter group
// swagger:model FilterGroup
type FilterGroup struct {

	// end
	End int32 `json:"end,omitempty"`

	// level
	Level int32 `json:"level,omitempty"`

	// start
	Start int32 `json:"start,omitempty"`
}

// Validate validates this filter group
func (m *FilterGroup) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FilterGroup) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FilterGroup) UnmarshalBinary(b []byte) error {
	var res FilterGroup
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
