// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// FormattedEventMessage Provides different formats of an event message
// swagger:model FormattedEventMessage
type FormattedEventMessage struct {

	// Gets or sets the html format of the message
	HTML string `json:"html,omitempty"`

	// Gets or sets the markdown format of the message
	Markdown string `json:"markdown,omitempty"`

	// Gets or sets the raw text of the message
	Text string `json:"text,omitempty"`
}

// Validate validates this formatted event message
func (m *FormattedEventMessage) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FormattedEventMessage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FormattedEventMessage) UnmarshalBinary(b []byte) error {
	var res FormattedEventMessage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
