// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GateUpdateMetadata gate update metadata
// swagger:model GateUpdateMetadata
type GateUpdateMetadata struct {

	// Comment.
	Comment string `json:"comment,omitempty"`

	// Name of gate to be ignored.
	GatesToIgnore []string `json:"gatesToIgnore"`
}

// Validate validates this gate update metadata
func (m *GateUpdateMetadata) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GateUpdateMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GateUpdateMetadata) UnmarshalBinary(b []byte) error {
	var res GateUpdateMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
