// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GitRepositoryRef git repository ref
// swagger:model GitRepositoryRef
type GitRepositoryRef struct {

	// Team Project Collection where this Fork resides
	Collection string `json:"collection,omitempty"`

	// id
	// Format: uuid
	ID strfmt.UUID `json:"id,omitempty"`

	// True if the repository was created as a fork
	IsFork bool `json:"isFork,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// project
	Project string `json:"project,omitempty"`

	// remote Url
	RemoteURL string `json:"remoteUrl,omitempty"`

	// ssh Url
	SSHURL string `json:"sshUrl,omitempty"`

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this git repository ref
func (m *GitRepositoryRef) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GitRepositoryRef) validateID(formats strfmt.Registry) error {

	if swag.IsZero(m.ID) { // not required
		return nil
	}

	if err := validate.FormatOf("id", "body", "uuid", m.ID.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GitRepositoryRef) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GitRepositoryRef) UnmarshalBinary(b []byte) error {
	var res GitRepositoryRef
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
