// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GraphUserMailAddressCreationContext Use this type to create a new user using the mail address as a reference to an existing user from an external AD or AAD backed provider. This is the subset of GraphUser fields required for creation of a GraphUser for the AD and AAD use case when looking up the user by its mail address in the backing provider.
// swagger:model GraphUserMailAddressCreationContext
type GraphUserMailAddressCreationContext struct {
	GraphUserCreationContext

	// mail address
	MailAddress string `json:"mailAddress,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *GraphUserMailAddressCreationContext) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 GraphUserCreationContext
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.GraphUserCreationContext = aO0

	// now for regular properties
	var propsGraphUserMailAddressCreationContext struct {
		MailAddress string `json:"mailAddress,omitempty"`
	}
	if err := swag.ReadJSON(raw, &propsGraphUserMailAddressCreationContext); err != nil {
		return err
	}
	m.MailAddress = propsGraphUserMailAddressCreationContext.MailAddress

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m GraphUserMailAddressCreationContext) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.GraphUserCreationContext)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	// now for regular properties
	var propsGraphUserMailAddressCreationContext struct {
		MailAddress string `json:"mailAddress,omitempty"`
	}
	propsGraphUserMailAddressCreationContext.MailAddress = m.MailAddress

	jsonDataPropsGraphUserMailAddressCreationContext, errGraphUserMailAddressCreationContext := swag.WriteJSON(propsGraphUserMailAddressCreationContext)
	if errGraphUserMailAddressCreationContext != nil {
		return nil, errGraphUserMailAddressCreationContext
	}
	_parts = append(_parts, jsonDataPropsGraphUserMailAddressCreationContext)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this graph user mail address creation context
func (m *GraphUserMailAddressCreationContext) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with GraphUserCreationContext
	if err := m.GraphUserCreationContext.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *GraphUserMailAddressCreationContext) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GraphUserMailAddressCreationContext) UnmarshalBinary(b []byte) error {
	var res GraphUserMailAddressCreationContext
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
