// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GraphGroup Graph group entity
// swagger:model GraphGroup
type GraphGroup struct {
	GraphMember

	// A short phrase to help human readers disambiguate groups with similar names
	Description string `json:"description,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *GraphGroup) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 GraphMember
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.GraphMember = aO0

	// now for regular properties
	var propsGraphGroup struct {
		Description string `json:"description,omitempty"`
	}
	if err := swag.ReadJSON(raw, &propsGraphGroup); err != nil {
		return err
	}
	m.Description = propsGraphGroup.Description

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m GraphGroup) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.GraphMember)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	// now for regular properties
	var propsGraphGroup struct {
		Description string `json:"description,omitempty"`
	}
	propsGraphGroup.Description = m.Description

	jsonDataPropsGraphGroup, errGraphGroup := swag.WriteJSON(propsGraphGroup)
	if errGraphGroup != nil {
		return nil, errGraphGroup
	}
	_parts = append(_parts, jsonDataPropsGraphGroup)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this graph group
func (m *GraphGroup) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with GraphMember
	if err := m.GraphMember.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *GraphGroup) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GraphGroup) UnmarshalBinary(b []byte) error {
	var res GraphGroup
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
