// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// JSONBlobIdentifierWithBlocks BlobIdentifier with block hashes formatted to be deserialzied for symbol service.
// swagger:model JsonBlobIdentifierWithBlocks
type JSONBlobIdentifierWithBlocks struct {

	// List of blob block hashes.
	BlockHashes []*JSONBlobBlockHash `json:"blockHashes"`

	// Array of blobId bytes.
	IdentifierValue []strfmt.Base64 `json:"identifierValue"`
}

// Validate validates this Json blob identifier with blocks
func (m *JSONBlobIdentifierWithBlocks) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBlockHashes(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIdentifierValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *JSONBlobIdentifierWithBlocks) validateBlockHashes(formats strfmt.Registry) error {

	if swag.IsZero(m.BlockHashes) { // not required
		return nil
	}

	for i := 0; i < len(m.BlockHashes); i++ {
		if swag.IsZero(m.BlockHashes[i]) { // not required
			continue
		}

		if m.BlockHashes[i] != nil {
			if err := m.BlockHashes[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("blockHashes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *JSONBlobIdentifierWithBlocks) validateIdentifierValue(formats strfmt.Registry) error {

	if swag.IsZero(m.IdentifierValue) { // not required
		return nil
	}

	for i := 0; i < len(m.IdentifierValue); i++ {

		// Format "byte" (base64 string) is already validated when unmarshalled

	}

	return nil
}

// MarshalBinary interface implementation
func (m *JSONBlobIdentifierWithBlocks) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JSONBlobIdentifierWithBlocks) UnmarshalBinary(b []byte) error {
	var res JSONBlobIdentifierWithBlocks
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
