// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OverridableRunSettings overridable run settings
// swagger:model OverridableRunSettings
type OverridableRunSettings struct {

	// load generator machines type
	// Enum: [default cltLoadAgent userLoadAgent]
	LoadGeneratorMachinesType interface{} `json:"loadGeneratorMachinesType,omitempty"`

	// static agent run settings
	StaticAgentRunSettings *StaticAgentRunSetting `json:"staticAgentRunSettings,omitempty"`
}

// Validate validates this overridable run settings
func (m *OverridableRunSettings) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStaticAgentRunSettings(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OverridableRunSettings) validateStaticAgentRunSettings(formats strfmt.Registry) error {

	if swag.IsZero(m.StaticAgentRunSettings) { // not required
		return nil
	}

	if m.StaticAgentRunSettings != nil {
		if err := m.StaticAgentRunSettings.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("staticAgentRunSettings")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OverridableRunSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OverridableRunSettings) UnmarshalBinary(b []byte) error {
	var res OverridableRunSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
