// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PackageVersionMetricsQuery Query to get package version metrics
// swagger:model PackageVersionMetricsQuery
type PackageVersionMetricsQuery struct {

	// List of package version ids
	PackageVersionIds []strfmt.UUID `json:"packageVersionIds"`
}

// Validate validates this package version metrics query
func (m *PackageVersionMetricsQuery) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePackageVersionIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PackageVersionMetricsQuery) validatePackageVersionIds(formats strfmt.Registry) error {

	if swag.IsZero(m.PackageVersionIds) { // not required
		return nil
	}

	for i := 0; i < len(m.PackageVersionIds); i++ {

		if err := validate.FormatOf("packageVersionIds"+"."+strconv.Itoa(i), "body", "uuid", m.PackageVersionIds[i].String(), formats); err != nil {
			return err
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PackageVersionMetricsQuery) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PackageVersionMetricsQuery) UnmarshalBinary(b []byte) error {
	var res PackageVersionMetricsQuery
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
