// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Plugin plugin
// swagger:model Plugin
type Plugin struct {
	MavenPomGav

	// configuration
	Configuration *PluginConfiguration `json:"configuration,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *Plugin) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 MavenPomGav
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.MavenPomGav = aO0

	// now for regular properties
	var propsPlugin struct {
		Configuration *PluginConfiguration `json:"configuration,omitempty"`
	}
	if err := swag.ReadJSON(raw, &propsPlugin); err != nil {
		return err
	}
	m.Configuration = propsPlugin.Configuration

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m Plugin) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.MavenPomGav)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	// now for regular properties
	var propsPlugin struct {
		Configuration *PluginConfiguration `json:"configuration,omitempty"`
	}
	propsPlugin.Configuration = m.Configuration

	jsonDataPropsPlugin, errPlugin := swag.WriteJSON(propsPlugin)
	if errPlugin != nil {
		return nil, errPlugin
	}
	_parts = append(_parts, jsonDataPropsPlugin)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this plugin
func (m *Plugin) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with MavenPomGav
	if err := m.MavenPomGav.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateConfiguration(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Plugin) validateConfiguration(formats strfmt.Registry) error {

	if swag.IsZero(m.Configuration) { // not required
		return nil
	}

	if m.Configuration != nil {
		if err := m.Configuration.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("configuration")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Plugin) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Plugin) UnmarshalBinary(b []byte) error {
	var res Plugin
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
