// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// SessionResponse session response
// swagger:model SessionResponse
type SessionResponse struct {

	// The unique identifier for the session
	SessionID string `json:"sessionId,omitempty"`

	// The name for the session
	SessionName string `json:"sessionName,omitempty"`
}

// Validate validates this session response
func (m *SessionResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SessionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SessionResponse) UnmarshalBinary(b []byte) error {
	var res SessionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
