// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TaskAgentManualUpdate task agent manual update
// swagger:model TaskAgentManualUpdate
type TaskAgentManualUpdate struct {
	TaskAgentUpdateReason
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *TaskAgentManualUpdate) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 TaskAgentUpdateReason
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.TaskAgentUpdateReason = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m TaskAgentManualUpdate) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.TaskAgentUpdateReason)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this task agent manual update
func (m *TaskAgentManualUpdate) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with TaskAgentUpdateReason
	if err := m.TaskAgentUpdateReason.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *TaskAgentManualUpdate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaskAgentManualUpdate) UnmarshalBinary(b []byte) error {
	var res TaskAgentManualUpdate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
