// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TaskAgentDelaySource task agent delay source
// swagger:model TaskAgentDelaySource
type TaskAgentDelaySource struct {

	// delays
	Delays []string `json:"delays"`

	// task agent
	TaskAgent *TaskAgentReference `json:"taskAgent,omitempty"`
}

// Validate validates this task agent delay source
func (m *TaskAgentDelaySource) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTaskAgent(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TaskAgentDelaySource) validateTaskAgent(formats strfmt.Registry) error {

	if swag.IsZero(m.TaskAgent) { // not required
		return nil
	}

	if m.TaskAgent != nil {
		if err := m.TaskAgent.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("taskAgent")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TaskAgentDelaySource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaskAgentDelaySource) UnmarshalBinary(b []byte) error {
	var res TaskAgentDelaySource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
