// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// WidgetTypesResponse widget types response
// swagger:model WidgetTypesResponse
type WidgetTypesResponse struct {

	// links
	Links *ReferenceLinks `json:"_links,omitempty"`

	// uri
	URI string `json:"uri,omitempty"`

	// widget types
	WidgetTypes []*WidgetMetadata `json:"widgetTypes"`
}

// Validate validates this widget types response
func (m *WidgetTypesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWidgetTypes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WidgetTypesResponse) validateLinks(formats strfmt.Registry) error {

	if swag.IsZero(m.Links) { // not required
		return nil
	}

	if m.Links != nil {
		if err := m.Links.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("_links")
			}
			return err
		}
	}

	return nil
}

func (m *WidgetTypesResponse) validateWidgetTypes(formats strfmt.Registry) error {

	if swag.IsZero(m.WidgetTypes) { // not required
		return nil
	}

	for i := 0; i < len(m.WidgetTypes); i++ {
		if swag.IsZero(m.WidgetTypes[i]) { // not required
			continue
		}

		if m.WidgetTypes[i] != nil {
			if err := m.WidgetTypes[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("widgetTypes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *WidgetTypesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WidgetTypesResponse) UnmarshalBinary(b []byte) error {
	var res WidgetTypesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
