// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// WidgetSize widget size
// swagger:model WidgetSize
type WidgetSize struct {

	// The Width of the widget, expressed in dashboard grid columns.
	ColumnSpan int32 `json:"columnSpan,omitempty"`

	// The height of the widget, expressed in dashboard grid rows.
	RowSpan int32 `json:"rowSpan,omitempty"`
}

// Validate validates this widget size
func (m *WidgetSize) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WidgetSize) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WidgetSize) UnmarshalBinary(b []byte) error {
	var res WidgetSize
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
