// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// WikiPageMove Request contract for Wiki Page Move.
// swagger:model WikiPageMove
type WikiPageMove struct {
	WikiPageMoveParameters

	// Resultant page of this page move operation.
	Page *WikiPage `json:"page,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *WikiPageMove) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 WikiPageMoveParameters
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.WikiPageMoveParameters = aO0

	// now for regular properties
	var propsWikiPageMove struct {
		Page *WikiPage `json:"page,omitempty"`
	}
	if err := swag.ReadJSON(raw, &propsWikiPageMove); err != nil {
		return err
	}
	m.Page = propsWikiPageMove.Page

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m WikiPageMove) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.WikiPageMoveParameters)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	// now for regular properties
	var propsWikiPageMove struct {
		Page *WikiPage `json:"page,omitempty"`
	}
	propsWikiPageMove.Page = m.Page

	jsonDataPropsWikiPageMove, errWikiPageMove := swag.WriteJSON(propsWikiPageMove)
	if errWikiPageMove != nil {
		return nil, errWikiPageMove
	}
	_parts = append(_parts, jsonDataPropsWikiPageMove)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this wiki page move
func (m *WikiPageMove) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with WikiPageMoveParameters
	if err := m.WikiPageMoveParameters.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WikiPageMove) validatePage(formats strfmt.Registry) error {

	if swag.IsZero(m.Page) { // not required
		return nil
	}

	if m.Page != nil {
		if err := m.Page.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("page")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *WikiPageMove) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WikiPageMove) UnmarshalBinary(b []byte) error {
	var res WikiPageMove
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
