// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// WikiCreateBaseParameters Base wiki creation parameters.
// swagger:model WikiCreateBaseParameters
type WikiCreateBaseParameters struct {

	// Folder path inside repository which is shown as Wiki. Not required for ProjectWiki type.
	MappedPath string `json:"mappedPath,omitempty"`

	// Wiki name.
	Name string `json:"name,omitempty"`

	// ID of the project in which the wiki is to be created.
	// Format: uuid
	ProjectID strfmt.UUID `json:"projectId,omitempty"`

	// ID of the git repository that backs up the wiki. Not required for ProjectWiki type.
	// Format: uuid
	RepositoryID strfmt.UUID `json:"repositoryId,omitempty"`

	// Type of the wiki.
	// Enum: [projectWiki codeWiki]
	Type interface{} `json:"type,omitempty"`
}

// Validate validates this wiki create base parameters
func (m *WikiCreateBaseParameters) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProjectID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRepositoryID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WikiCreateBaseParameters) validateProjectID(formats strfmt.Registry) error {

	if swag.IsZero(m.ProjectID) { // not required
		return nil
	}

	if err := validate.FormatOf("projectId", "body", "uuid", m.ProjectID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *WikiCreateBaseParameters) validateRepositoryID(formats strfmt.Registry) error {

	if swag.IsZero(m.RepositoryID) { // not required
		return nil
	}

	if err := validate.FormatOf("repositoryId", "body", "uuid", m.RepositoryID.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *WikiCreateBaseParameters) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WikiCreateBaseParameters) UnmarshalBinary(b []byte) error {
	var res WikiCreateBaseParameters
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
