// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// WorkItemFieldOperation Describes a work item field operation.
// swagger:model WorkItemFieldOperation
type WorkItemFieldOperation struct {

	// Friendly name of the operation.
	Name string `json:"name,omitempty"`

	// Reference name of the operation.
	ReferenceName string `json:"referenceName,omitempty"`
}

// Validate validates this work item field operation
func (m *WorkItemFieldOperation) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WorkItemFieldOperation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WorkItemFieldOperation) UnmarshalBinary(b []byte) error {
	var res WorkItemFieldOperation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
