// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// WorkItemTrackingReference work item tracking reference
// swagger:model WorkItemTrackingReference
type WorkItemTrackingReference struct {
	WorkItemTrackingResource

	// The name.
	Name string `json:"name,omitempty"`

	// The reference name.
	ReferenceName string `json:"referenceName,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *WorkItemTrackingReference) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 WorkItemTrackingResource
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.WorkItemTrackingResource = aO0

	// now for regular properties
	var propsWorkItemTrackingReference struct {
		Name string `json:"name,omitempty"`

		ReferenceName string `json:"referenceName,omitempty"`
	}
	if err := swag.ReadJSON(raw, &propsWorkItemTrackingReference); err != nil {
		return err
	}
	m.Name = propsWorkItemTrackingReference.Name

	m.ReferenceName = propsWorkItemTrackingReference.ReferenceName

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m WorkItemTrackingReference) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.WorkItemTrackingResource)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	// now for regular properties
	var propsWorkItemTrackingReference struct {
		Name string `json:"name,omitempty"`

		ReferenceName string `json:"referenceName,omitempty"`
	}
	propsWorkItemTrackingReference.Name = m.Name

	propsWorkItemTrackingReference.ReferenceName = m.ReferenceName

	jsonDataPropsWorkItemTrackingReference, errWorkItemTrackingReference := swag.WriteJSON(propsWorkItemTrackingReference)
	if errWorkItemTrackingReference != nil {
		return nil, errWorkItemTrackingReference
	}
	_parts = append(_parts, jsonDataPropsWorkItemTrackingReference)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this work item tracking reference
func (m *WorkItemTrackingReference) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with WorkItemTrackingResource
	if err := m.WorkItemTrackingResource.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *WorkItemTrackingReference) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WorkItemTrackingReference) UnmarshalBinary(b []byte) error {
	var res WorkItemTrackingReference
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
