// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// WorkItemNextStateOnTransition Describes the next state for a work item.
// swagger:model WorkItemNextStateOnTransition
type WorkItemNextStateOnTransition struct {

	// Error code if there is no next state transition possible.
	ErrorCode string `json:"errorCode,omitempty"`

	// Work item ID.
	ID int32 `json:"id,omitempty"`

	// Error message if there is no next state transition possible.
	Message string `json:"message,omitempty"`

	// Name of the next state on transition.
	StateOnTransition string `json:"stateOnTransition,omitempty"`
}

// Validate validates this work item next state on transition
func (m *WorkItemNextStateOnTransition) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WorkItemNextStateOnTransition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WorkItemNextStateOnTransition) UnmarshalBinary(b []byte) error {
	var res WorkItemNextStateOnTransition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
