// Code generated by go-swagger; DO NOT EDIT.

package test_runs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetTestRunsReader is a Reader for the GetTestRuns structure.
type GetTestRunsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTestRunsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetTestRunsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetTestRunsOK creates a GetTestRunsOK with default headers values
func NewGetTestRunsOK() *GetTestRunsOK {
	return &GetTestRunsOK{}
}

/*GetTestRunsOK handles this case with default header values.

successful operation
*/
type GetTestRunsOK struct {
	Payload interface{}
}

func (o *GetTestRunsOK) Error() string {
	return fmt.Sprintf("[GET /{organization}/_apis/clt/testruns][%d] getTestRunsOK  %+v", 200, o.Payload)
}

func (o *GetTestRunsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
