// Code generated by go-swagger; DO NOT EDIT.

package backlogs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetBacklogParams creates a new GetBacklogParams object
// with the default values initialized.
func NewGetBacklogParams() *GetBacklogParams {
	var ()
	return &GetBacklogParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetBacklogParamsWithTimeout creates a new GetBacklogParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetBacklogParamsWithTimeout(timeout time.Duration) *GetBacklogParams {
	var ()
	return &GetBacklogParams{

		timeout: timeout,
	}
}

// NewGetBacklogParamsWithContext creates a new GetBacklogParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetBacklogParamsWithContext(ctx context.Context) *GetBacklogParams {
	var ()
	return &GetBacklogParams{

		Context: ctx,
	}
}

// NewGetBacklogParamsWithHTTPClient creates a new GetBacklogParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetBacklogParamsWithHTTPClient(client *http.Client) *GetBacklogParams {
	var ()
	return &GetBacklogParams{
		HTTPClient: client,
	}
}

/*GetBacklogParams contains all the parameters to send to the API endpoint
for the get backlog operation typically these are written to a http.Request
*/
type GetBacklogParams struct {

	/*APIVersion
	  Version of the API to use.  This should be set to '5.1-preview.1' to use this version of the api.

	*/
	APIVersion string
	/*ID
	  The id of the backlog level

	*/
	ID string
	/*Organization
	  The name of the Azure DevOps organization.

	*/
	Organization string
	/*Project
	  Project ID or project name

	*/
	Project string
	/*Team
	  Team ID or team name

	*/
	Team string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get backlog params
func (o *GetBacklogParams) WithTimeout(timeout time.Duration) *GetBacklogParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get backlog params
func (o *GetBacklogParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get backlog params
func (o *GetBacklogParams) WithContext(ctx context.Context) *GetBacklogParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get backlog params
func (o *GetBacklogParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get backlog params
func (o *GetBacklogParams) WithHTTPClient(client *http.Client) *GetBacklogParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get backlog params
func (o *GetBacklogParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIVersion adds the aPIVersion to the get backlog params
func (o *GetBacklogParams) WithAPIVersion(aPIVersion string) *GetBacklogParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the get backlog params
func (o *GetBacklogParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithID adds the id to the get backlog params
func (o *GetBacklogParams) WithID(id string) *GetBacklogParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get backlog params
func (o *GetBacklogParams) SetID(id string) {
	o.ID = id
}

// WithOrganization adds the organization to the get backlog params
func (o *GetBacklogParams) WithOrganization(organization string) *GetBacklogParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the get backlog params
func (o *GetBacklogParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithProject adds the project to the get backlog params
func (o *GetBacklogParams) WithProject(project string) *GetBacklogParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the get backlog params
func (o *GetBacklogParams) SetProject(project string) {
	o.Project = project
}

// WithTeam adds the team to the get backlog params
func (o *GetBacklogParams) WithTeam(team string) *GetBacklogParams {
	o.SetTeam(team)
	return o
}

// SetTeam adds the team to the get backlog params
func (o *GetBacklogParams) SetTeam(team string) {
	o.Team = team
}

// WriteToRequest writes these params to a swagger request
func (o *GetBacklogParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	// path param team
	if err := r.SetPathParam("team", o.Team); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
