// Code generated by go-swagger; DO NOT EDIT.

package plans

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "azure-devops/5.1/models"
)

// PutOrganizationProjectApisWorkPlansIDReader is a Reader for the PutOrganizationProjectApisWorkPlansID structure.
type PutOrganizationProjectApisWorkPlansIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutOrganizationProjectApisWorkPlansIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutOrganizationProjectApisWorkPlansIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutOrganizationProjectApisWorkPlansIDOK creates a PutOrganizationProjectApisWorkPlansIDOK with default headers values
func NewPutOrganizationProjectApisWorkPlansIDOK() *PutOrganizationProjectApisWorkPlansIDOK {
	return &PutOrganizationProjectApisWorkPlansIDOK{}
}

/*PutOrganizationProjectApisWorkPlansIDOK handles this case with default header values.

successful operation
*/
type PutOrganizationProjectApisWorkPlansIDOK struct {
	Payload *models.Plan
}

func (o *PutOrganizationProjectApisWorkPlansIDOK) Error() string {
	return fmt.Sprintf("[PUT /{organization}/{project}/_apis/work/plans/{id}][%d] putOrganizationProjectApisWorkPlansIdOK  %+v", 200, o.Payload)
}

func (o *PutOrganizationProjectApisWorkPlansIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Plan)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
