// Code generated by go-swagger; DO NOT EDIT.

package definitions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "azure-devops/5.1/models"
)

// GetDefinitionRevisionsReader is a Reader for the GetDefinitionRevisions structure.
type GetDefinitionRevisionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDefinitionRevisionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDefinitionRevisionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDefinitionRevisionsOK creates a GetDefinitionRevisionsOK with default headers values
func NewGetDefinitionRevisionsOK() *GetDefinitionRevisionsOK {
	return &GetDefinitionRevisionsOK{}
}

/*GetDefinitionRevisionsOK handles this case with default header values.

successful operation
*/
type GetDefinitionRevisionsOK struct {
	Payload []*models.BuildDefinitionRevision
}

func (o *GetDefinitionRevisionsOK) Error() string {
	return fmt.Sprintf("[GET /{organization}/{project}/_apis/build/definitions/{definitionId}/revisions][%d] getDefinitionRevisionsOK  %+v", 200, o.Payload)
}

func (o *GetDefinitionRevisionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
