// Code generated by go-swagger; DO NOT EDIT.

package releases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetReleaseEnvironmentParams creates a new GetReleaseEnvironmentParams object
// with the default values initialized.
func NewGetReleaseEnvironmentParams() *GetReleaseEnvironmentParams {
	var ()
	return &GetReleaseEnvironmentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetReleaseEnvironmentParamsWithTimeout creates a new GetReleaseEnvironmentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetReleaseEnvironmentParamsWithTimeout(timeout time.Duration) *GetReleaseEnvironmentParams {
	var ()
	return &GetReleaseEnvironmentParams{

		timeout: timeout,
	}
}

// NewGetReleaseEnvironmentParamsWithContext creates a new GetReleaseEnvironmentParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetReleaseEnvironmentParamsWithContext(ctx context.Context) *GetReleaseEnvironmentParams {
	var ()
	return &GetReleaseEnvironmentParams{

		Context: ctx,
	}
}

// NewGetReleaseEnvironmentParamsWithHTTPClient creates a new GetReleaseEnvironmentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetReleaseEnvironmentParamsWithHTTPClient(client *http.Client) *GetReleaseEnvironmentParams {
	var ()
	return &GetReleaseEnvironmentParams{
		HTTPClient: client,
	}
}

/*GetReleaseEnvironmentParams contains all the parameters to send to the API endpoint
for the get release environment operation typically these are written to a http.Request
*/
type GetReleaseEnvironmentParams struct {

	/*APIVersion
	  Version of the API to use.  This should be set to '5.1-preview.6' to use this version of the api.

	*/
	APIVersion string
	/*EnvironmentID
	  Id of the release environment.

	*/
	EnvironmentID int32
	/*Organization
	  The name of the Azure DevOps organization.

	*/
	Organization string
	/*Project
	  Project ID or project name

	*/
	Project string
	/*ReleaseID
	  Id of the release.

	*/
	ReleaseID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get release environment params
func (o *GetReleaseEnvironmentParams) WithTimeout(timeout time.Duration) *GetReleaseEnvironmentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get release environment params
func (o *GetReleaseEnvironmentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get release environment params
func (o *GetReleaseEnvironmentParams) WithContext(ctx context.Context) *GetReleaseEnvironmentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get release environment params
func (o *GetReleaseEnvironmentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get release environment params
func (o *GetReleaseEnvironmentParams) WithHTTPClient(client *http.Client) *GetReleaseEnvironmentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get release environment params
func (o *GetReleaseEnvironmentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIVersion adds the aPIVersion to the get release environment params
func (o *GetReleaseEnvironmentParams) WithAPIVersion(aPIVersion string) *GetReleaseEnvironmentParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the get release environment params
func (o *GetReleaseEnvironmentParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithEnvironmentID adds the environmentID to the get release environment params
func (o *GetReleaseEnvironmentParams) WithEnvironmentID(environmentID int32) *GetReleaseEnvironmentParams {
	o.SetEnvironmentID(environmentID)
	return o
}

// SetEnvironmentID adds the environmentId to the get release environment params
func (o *GetReleaseEnvironmentParams) SetEnvironmentID(environmentID int32) {
	o.EnvironmentID = environmentID
}

// WithOrganization adds the organization to the get release environment params
func (o *GetReleaseEnvironmentParams) WithOrganization(organization string) *GetReleaseEnvironmentParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the get release environment params
func (o *GetReleaseEnvironmentParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithProject adds the project to the get release environment params
func (o *GetReleaseEnvironmentParams) WithProject(project string) *GetReleaseEnvironmentParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the get release environment params
func (o *GetReleaseEnvironmentParams) SetProject(project string) {
	o.Project = project
}

// WithReleaseID adds the releaseID to the get release environment params
func (o *GetReleaseEnvironmentParams) WithReleaseID(releaseID int32) *GetReleaseEnvironmentParams {
	o.SetReleaseID(releaseID)
	return o
}

// SetReleaseID adds the releaseId to the get release environment params
func (o *GetReleaseEnvironmentParams) SetReleaseID(releaseID int32) {
	o.ReleaseID = releaseID
}

// WriteToRequest writes these params to a swagger request
func (o *GetReleaseEnvironmentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	// path param environmentId
	if err := r.SetPathParam("environmentId", swag.FormatInt32(o.EnvironmentID)); err != nil {
		return err
	}

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	// path param releaseId
	if err := r.SetPathParam("releaseId", swag.FormatInt32(o.ReleaseID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
