// Code generated by go-swagger; DO NOT EDIT.

package releases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "azure-devops/5.1/models"
)

// UpdateReleaseReader is a Reader for the UpdateRelease structure.
type UpdateReleaseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateReleaseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpdateReleaseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateReleaseOK creates a UpdateReleaseOK with default headers values
func NewUpdateReleaseOK() *UpdateReleaseOK {
	return &UpdateReleaseOK{}
}

/*UpdateReleaseOK handles this case with default header values.

successful operation
*/
type UpdateReleaseOK struct {
	Payload *models.Release
}

func (o *UpdateReleaseOK) Error() string {
	return fmt.Sprintf("[PUT /{organization}/{project}/_apis/release/releases/{releaseId}][%d] updateReleaseOK  %+v", 200, o.Payload)
}

func (o *UpdateReleaseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Release)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
