// Code generated by go-swagger; DO NOT EDIT.

package consumers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "azure-devops/5.1/models"
)

// GetConsumerActionReader is a Reader for the GetConsumerAction structure.
type GetConsumerActionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetConsumerActionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetConsumerActionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetConsumerActionOK creates a GetConsumerActionOK with default headers values
func NewGetConsumerActionOK() *GetConsumerActionOK {
	return &GetConsumerActionOK{}
}

/*GetConsumerActionOK handles this case with default header values.

successful operation
*/
type GetConsumerActionOK struct {
	Payload *models.ConsumerAction
}

func (o *GetConsumerActionOK) Error() string {
	return fmt.Sprintf("[GET /{organization}/_apis/hooks/consumers/{consumerId}/actions/{consumerActionId}][%d] getConsumerActionOK  %+v", 200, o.Payload)
}

func (o *GetConsumerActionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ConsumerAction)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
