// Code generated by go-swagger; DO NOT EDIT.

package builds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetBuildLogReader is a Reader for the GetBuildLog structure.
type GetBuildLogReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBuildLogReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetBuildLogOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetBuildLogOK creates a GetBuildLogOK with default headers values
func NewGetBuildLogOK() *GetBuildLogOK {
	return &GetBuildLogOK{}
}

/*GetBuildLogOK handles this case with default header values.

successful operation
*/
type GetBuildLogOK struct {
	Payload string
}

func (o *GetBuildLogOK) Error() string {
	return fmt.Sprintf("[GET /{organization}/{project}/_apis/build/builds/{buildId}/logs/{logId}][%d] getBuildLogOK  %+v", 200, o.Payload)
}

func (o *GetBuildLogOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
