// Code generated by go-swagger; DO NOT EDIT.

package reporting_work_item_revisions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "azure-devops/5.1/models"
)

// ReadReportingRevisionsGetReader is a Reader for the ReadReportingRevisionsGet structure.
type ReadReportingRevisionsGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReadReportingRevisionsGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewReadReportingRevisionsGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewReadReportingRevisionsGetOK creates a ReadReportingRevisionsGetOK with default headers values
func NewReadReportingRevisionsGetOK() *ReadReportingRevisionsGetOK {
	return &ReadReportingRevisionsGetOK{}
}

/*ReadReportingRevisionsGetOK handles this case with default header values.

successful operation
*/
type ReadReportingRevisionsGetOK struct {
	Payload *models.ReportingWorkItemRevisionsBatch
}

func (o *ReadReportingRevisionsGetOK) Error() string {
	return fmt.Sprintf("[GET /{organization}/{project}/_apis/wit/reporting/workitemrevisions][%d] readReportingRevisionsGetOK  %+v", 200, o.Payload)
}

func (o *ReadReportingRevisionsGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ReportingWorkItemRevisionsBatch)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
