// Code generated by go-swagger; DO NOT EDIT.

package token_revocations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new token revocations API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for token revocations API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
RevokeAuthorizations Revokes the listed OAuth authorizations.
*/
func (a *Client) RevokeAuthorizations(params *RevokeAuthorizationsParams, authInfo runtime.ClientAuthInfoWriter) (*RevokeAuthorizationsNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewRevokeAuthorizationsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "Revoke Authorizations",
		Method:             "POST",
		PathPattern:        "/_apis/tokenadministration/tokenrevocations",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &RevokeAuthorizationsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*RevokeAuthorizationsNoContent), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
