// Code generated by go-swagger; DO NOT EDIT.

package installed_extensions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UninstallExtensionByNameReader is a Reader for the UninstallExtensionByName structure.
type UninstallExtensionByNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UninstallExtensionByNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUninstallExtensionByNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUninstallExtensionByNameOK creates a UninstallExtensionByNameOK with default headers values
func NewUninstallExtensionByNameOK() *UninstallExtensionByNameOK {
	return &UninstallExtensionByNameOK{}
}

/*UninstallExtensionByNameOK handles this case with default header values.

successful operation
*/
type UninstallExtensionByNameOK struct {
}

func (o *UninstallExtensionByNameOK) Error() string {
	return fmt.Sprintf("[DELETE /{organization}/_apis/extensionmanagement/installedextensionsbyname/{publisherName}/{extensionName}][%d] uninstallExtensionByNameOK ", 200)
}

func (o *UninstallExtensionByNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
