// Code generated by go-swagger; DO NOT EDIT.

package nu_get

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeletePackageVersionFromRecycleBinParams creates a new DeletePackageVersionFromRecycleBinParams object
// with the default values initialized.
func NewDeletePackageVersionFromRecycleBinParams() *DeletePackageVersionFromRecycleBinParams {
	var ()
	return &DeletePackageVersionFromRecycleBinParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeletePackageVersionFromRecycleBinParamsWithTimeout creates a new DeletePackageVersionFromRecycleBinParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeletePackageVersionFromRecycleBinParamsWithTimeout(timeout time.Duration) *DeletePackageVersionFromRecycleBinParams {
	var ()
	return &DeletePackageVersionFromRecycleBinParams{

		timeout: timeout,
	}
}

// NewDeletePackageVersionFromRecycleBinParamsWithContext creates a new DeletePackageVersionFromRecycleBinParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeletePackageVersionFromRecycleBinParamsWithContext(ctx context.Context) *DeletePackageVersionFromRecycleBinParams {
	var ()
	return &DeletePackageVersionFromRecycleBinParams{

		Context: ctx,
	}
}

// NewDeletePackageVersionFromRecycleBinParamsWithHTTPClient creates a new DeletePackageVersionFromRecycleBinParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeletePackageVersionFromRecycleBinParamsWithHTTPClient(client *http.Client) *DeletePackageVersionFromRecycleBinParams {
	var ()
	return &DeletePackageVersionFromRecycleBinParams{
		HTTPClient: client,
	}
}

/*DeletePackageVersionFromRecycleBinParams contains all the parameters to send to the API endpoint
for the delete package version from recycle bin operation typically these are written to a http.Request
*/
type DeletePackageVersionFromRecycleBinParams struct {

	/*APIVersion
	  Version of the API to use.  This should be set to '5.1-preview.1' to use this version of the api.

	*/
	APIVersion string
	/*FeedID
	  Name or ID of the feed.

	*/
	FeedID string
	/*Organization
	  The name of the Azure DevOps organization.

	*/
	Organization string
	/*PackageName
	  Name of the package.

	*/
	PackageName string
	/*PackageVersion
	  Version of the package.

	*/
	PackageVersion string
	/*Project
	  Project ID or project name

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete package version from recycle bin params
func (o *DeletePackageVersionFromRecycleBinParams) WithTimeout(timeout time.Duration) *DeletePackageVersionFromRecycleBinParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete package version from recycle bin params
func (o *DeletePackageVersionFromRecycleBinParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete package version from recycle bin params
func (o *DeletePackageVersionFromRecycleBinParams) WithContext(ctx context.Context) *DeletePackageVersionFromRecycleBinParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete package version from recycle bin params
func (o *DeletePackageVersionFromRecycleBinParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete package version from recycle bin params
func (o *DeletePackageVersionFromRecycleBinParams) WithHTTPClient(client *http.Client) *DeletePackageVersionFromRecycleBinParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete package version from recycle bin params
func (o *DeletePackageVersionFromRecycleBinParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIVersion adds the aPIVersion to the delete package version from recycle bin params
func (o *DeletePackageVersionFromRecycleBinParams) WithAPIVersion(aPIVersion string) *DeletePackageVersionFromRecycleBinParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the delete package version from recycle bin params
func (o *DeletePackageVersionFromRecycleBinParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithFeedID adds the feedID to the delete package version from recycle bin params
func (o *DeletePackageVersionFromRecycleBinParams) WithFeedID(feedID string) *DeletePackageVersionFromRecycleBinParams {
	o.SetFeedID(feedID)
	return o
}

// SetFeedID adds the feedId to the delete package version from recycle bin params
func (o *DeletePackageVersionFromRecycleBinParams) SetFeedID(feedID string) {
	o.FeedID = feedID
}

// WithOrganization adds the organization to the delete package version from recycle bin params
func (o *DeletePackageVersionFromRecycleBinParams) WithOrganization(organization string) *DeletePackageVersionFromRecycleBinParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the delete package version from recycle bin params
func (o *DeletePackageVersionFromRecycleBinParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithPackageName adds the packageName to the delete package version from recycle bin params
func (o *DeletePackageVersionFromRecycleBinParams) WithPackageName(packageName string) *DeletePackageVersionFromRecycleBinParams {
	o.SetPackageName(packageName)
	return o
}

// SetPackageName adds the packageName to the delete package version from recycle bin params
func (o *DeletePackageVersionFromRecycleBinParams) SetPackageName(packageName string) {
	o.PackageName = packageName
}

// WithPackageVersion adds the packageVersion to the delete package version from recycle bin params
func (o *DeletePackageVersionFromRecycleBinParams) WithPackageVersion(packageVersion string) *DeletePackageVersionFromRecycleBinParams {
	o.SetPackageVersion(packageVersion)
	return o
}

// SetPackageVersion adds the packageVersion to the delete package version from recycle bin params
func (o *DeletePackageVersionFromRecycleBinParams) SetPackageVersion(packageVersion string) {
	o.PackageVersion = packageVersion
}

// WithProject adds the project to the delete package version from recycle bin params
func (o *DeletePackageVersionFromRecycleBinParams) WithProject(project string) *DeletePackageVersionFromRecycleBinParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the delete package version from recycle bin params
func (o *DeletePackageVersionFromRecycleBinParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *DeletePackageVersionFromRecycleBinParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	// path param feedId
	if err := r.SetPathParam("feedId", o.FeedID); err != nil {
		return err
	}

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param packageName
	if err := r.SetPathParam("packageName", o.PackageName); err != nil {
		return err
	}

	// path param packageVersion
	if err := r.SetPathParam("packageVersion", o.PackageVersion); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
