// Code generated by go-swagger; DO NOT EDIT.

package nu_get

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "azure-devops/5.1/models"
)

// NewUpdatePackageVersionParams creates a new UpdatePackageVersionParams object
// with the default values initialized.
func NewUpdatePackageVersionParams() *UpdatePackageVersionParams {
	var ()
	return &UpdatePackageVersionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdatePackageVersionParamsWithTimeout creates a new UpdatePackageVersionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdatePackageVersionParamsWithTimeout(timeout time.Duration) *UpdatePackageVersionParams {
	var ()
	return &UpdatePackageVersionParams{

		timeout: timeout,
	}
}

// NewUpdatePackageVersionParamsWithContext creates a new UpdatePackageVersionParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdatePackageVersionParamsWithContext(ctx context.Context) *UpdatePackageVersionParams {
	var ()
	return &UpdatePackageVersionParams{

		Context: ctx,
	}
}

// NewUpdatePackageVersionParamsWithHTTPClient creates a new UpdatePackageVersionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdatePackageVersionParamsWithHTTPClient(client *http.Client) *UpdatePackageVersionParams {
	var ()
	return &UpdatePackageVersionParams{
		HTTPClient: client,
	}
}

/*UpdatePackageVersionParams contains all the parameters to send to the API endpoint
for the update package version operation typically these are written to a http.Request
*/
type UpdatePackageVersionParams struct {

	/*APIVersion
	  Version of the API to use.  This should be set to '5.1-preview.1' to use this version of the api.

	*/
	APIVersion string
	/*Body
	  New state to apply to the referenced package.

	*/
	Body *models.PackageVersionDetails
	/*FeedID
	  Name or ID of the feed.

	*/
	FeedID string
	/*Organization
	  The name of the Azure DevOps organization.

	*/
	Organization string
	/*PackageName
	  Name of the package to update.

	*/
	PackageName string
	/*PackageVersion
	  Version of the package to update.

	*/
	PackageVersion string
	/*Project
	  Project ID or project name

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update package version params
func (o *UpdatePackageVersionParams) WithTimeout(timeout time.Duration) *UpdatePackageVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update package version params
func (o *UpdatePackageVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update package version params
func (o *UpdatePackageVersionParams) WithContext(ctx context.Context) *UpdatePackageVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update package version params
func (o *UpdatePackageVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update package version params
func (o *UpdatePackageVersionParams) WithHTTPClient(client *http.Client) *UpdatePackageVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update package version params
func (o *UpdatePackageVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIVersion adds the aPIVersion to the update package version params
func (o *UpdatePackageVersionParams) WithAPIVersion(aPIVersion string) *UpdatePackageVersionParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the update package version params
func (o *UpdatePackageVersionParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithBody adds the body to the update package version params
func (o *UpdatePackageVersionParams) WithBody(body *models.PackageVersionDetails) *UpdatePackageVersionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update package version params
func (o *UpdatePackageVersionParams) SetBody(body *models.PackageVersionDetails) {
	o.Body = body
}

// WithFeedID adds the feedID to the update package version params
func (o *UpdatePackageVersionParams) WithFeedID(feedID string) *UpdatePackageVersionParams {
	o.SetFeedID(feedID)
	return o
}

// SetFeedID adds the feedId to the update package version params
func (o *UpdatePackageVersionParams) SetFeedID(feedID string) {
	o.FeedID = feedID
}

// WithOrganization adds the organization to the update package version params
func (o *UpdatePackageVersionParams) WithOrganization(organization string) *UpdatePackageVersionParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the update package version params
func (o *UpdatePackageVersionParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithPackageName adds the packageName to the update package version params
func (o *UpdatePackageVersionParams) WithPackageName(packageName string) *UpdatePackageVersionParams {
	o.SetPackageName(packageName)
	return o
}

// SetPackageName adds the packageName to the update package version params
func (o *UpdatePackageVersionParams) SetPackageName(packageName string) {
	o.PackageName = packageName
}

// WithPackageVersion adds the packageVersion to the update package version params
func (o *UpdatePackageVersionParams) WithPackageVersion(packageVersion string) *UpdatePackageVersionParams {
	o.SetPackageVersion(packageVersion)
	return o
}

// SetPackageVersion adds the packageVersion to the update package version params
func (o *UpdatePackageVersionParams) SetPackageVersion(packageVersion string) {
	o.PackageVersion = packageVersion
}

// WithProject adds the project to the update package version params
func (o *UpdatePackageVersionParams) WithProject(project string) *UpdatePackageVersionParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the update package version params
func (o *UpdatePackageVersionParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *UpdatePackageVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param api-version
	qrAPIVersion := o.APIVersion
	qAPIVersion := qrAPIVersion
	if qAPIVersion != "" {
		if err := r.SetQueryParam("api-version", qAPIVersion); err != nil {
			return err
		}
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param feedId
	if err := r.SetPathParam("feedId", o.FeedID); err != nil {
		return err
	}

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param packageName
	if err := r.SetPathParam("packageName", o.PackageName); err != nil {
		return err
	}

	// path param packageVersion
	if err := r.SetPathParam("packageVersion", o.PackageVersion); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
